version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: partypilot-db
    environment:
      POSTGRES_USER: partypilot
      POSTGRES_PASSWORD: partypilot
      POSTGRES_DB: partypilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 